### ISSUE TITLE
Plugin unavailable issue

### ISSUE THREAD

**Issue by ricardlira** [VolkovLabs/volkovlabs-env-datasource#37]
Hello Volkovlabs teams!

I really appreciate the tools you guys are making available, they are being deployed in our control systems based on Grafana. I work for a Brazilian electricity utility in a project related to real-time measurements. We are using Grafana as our main UI. 

One of the plugins I need is the datasrouce you guys are doing. However, after successful installation in my Grafana 9.5.15 version (SO: RHEL) the health test reports "Plugin unavailable". Grafana was able to list the "Environment Variables" plugin (signed) successfully but the test failed. I also added this plugin in the "allowed unsigned plugins" in grafana.ini section, just in case. 

I have tried two different versions of the plugin but with the same outcome:
volkovlabs-env-datasource-3.1.0.zip
volkovlabs-env-datasource-2.0.0.zip

Any guidance here in order to unlock the issue? 

Thanks!
Ricardo

**Comment by ricardlira** [comment]
This is what the browser F12 can see: 
![image](https://github.com/VolkovLabs/volkovlabs-env-datasource/assets/172292159/5c16423d-71a9-4654-aee0-11d0ba4d7b74)

**Comment by mikhail-vl** [comment]
@ricardlira How do you deploy Grafana?

  Backend data sources require Golang executable to run in addition to the React plugin, check in the logs that the executable was started successfully.

**Comment by ricardlira** [comment]
Hi Mikhail, 

Thanks for your reply. I installed Grafana 11 directly on RHEL server using the command line: 
**_rpm -ivh grafana-enterprise-11.0.0-1.x86_64.rpm_**

I'm not aware of any other required plugin to run. 
Any help to to proceed with this extra check (golang... react plugin...)

Do you have any documentation with detailed installing steps directly on a server? 

Thanks
Ricardo
