### ISSUE TITLE
Unable to load env-datasource plugin after install, signature problem results in status invalid.

### ISSUE THREAD

**Issue by Double-G** [VolkovLabs/volkovlabs-env-datasource#8]
Hello,

I have been unable to load and use the volkovlabs-env-datasource after install. I first attempted the README install command which overrides the default repo but it results in a 404 not found error.
> grafana-cli --repo https://volkovlabs.io/plugins plugins install volkovlabs-env-datasource

I also attempted to install with a grafana-cli --pluginUrl command referencing the newest zip file which succeeds to install but I cannot resolve the following error:

`msg="Skipping loading plugin due to problem with signature" pluginID=volkovlabs-env-datasource status=invalid`

I have added the `allow_loading_unsigned_plugins=volkovlabs-env-datasource` value to the grafana.ini but this does not resolve the signature issue. I tested with both 2.1.0 and 2.0.0 versions.

I was attempting to add the plugin to both Grafana version 9.0.7 and 9.1.0.

Appreciate any help, thank you.

**Comment by mikhail-vl** [comment]
Hello @Double-G,

  Thank you for opening the issue. Looks like me missed a step to upload the latest version to our Private Repository, it's fixed now. I was able to install it successfully.

  Our private plugins are signed to use for default Grafana URL `http://localhost:3000/`, if you are using different name and/or port you need to set `allow_loading_unsigned_plugins` and remove `MANIFEST.txt` file inside the plugin folder.

  Please let me know if it helps.

**Comment by Double-G** [comment]
Thank you for the quick response. I didn't realize I needed to remove the `MANIFEST` file to utilize the `allow_loading_unsigned_plugins` setting. Thank you for the link fix and the information.

**Comment by mikhail-vl** [comment]
@Double-G Thank you for confirming.

I will update the README file with instructions linked to our tutorial: https://volkovlabs.io/plugins/grafana-allow-unsigned/
